### Numpy

In [ ]:
numpy >> Numerical Python

In [7]:
import numpy as np
import pandas as pd

### Application

In [ ]:
1. Linear Algebra
2. Statistics
3. Trigonometry
4. Logarithmic
5. Image Processing
6. Matrix Operation

### Properties 

In [ ]:
1. It is collection of homogeneous datatype
2. Numpy is faster than List(Python)
3. Numpy is written in C language(partially written in Python)
4. C language is always faster than Python 
5. Mutable >> Add, delete, update

int >> float >> complex >> str

DataType:
    numpy.ndarray >> n-dimensional array

### Numpy Functions

In [ ]:
1. np.array():
    np.array(List, dtype = int, ndmin = 2)
    np.array(Tuple, dtype = int, ndmin = 2)

2. array.ndim
3. array.dtype
4. Array to List:
    array.tolist()
    list(array) # 1D
5. np.iinfo('int')

### Type Casting in Numpy

In [ ]:
int >> float
float >> int
int >> complex
float >> complex
complex !>> int
complex !>> float

In [193]:
array1 = np.array([3,4,5,6,7])
array1

array([3, 4, 5, 6, 7])

In [195]:
array1 = np.array((3,4,5,6,7))
array1

array([3, 4, 5, 6, 7])

In [197]:
array1 = np.array({3,4,5,6,7,6,7})
array1

array({3, 4, 5, 6, 7}, dtype=object)

In [12]:
array1 = np.array([3,4,5,6,7])
type(array1)

numpy.ndarray

In [10]:
array1 = np.array([3,4,5,6,7])
print(array1)

[3 4 5 6 7]


In [15]:
array1 = np.array(['a','b','c'])
array1

array(['a', 'b', 'c'], dtype='<U1')

In [ ]:
array1 = np.array(['a','b','c'])
array1

In [17]:
list1 = ['a','b','c']
list1

['a', 'b', 'c']

In [19]:
list1 = ['a','b','c',2,5,6,7,8.5,9.23]
list1

['a', 'b', 'c', 2, 5, 6, 7, 8.5, 9.23]

In [21]:
array1 = np.array([4,5,6])
array1

array([4, 5, 6])

In [24]:
array1 = np.array([4,5,6,8.9])
array1

array([4. , 5. , 6. , 8.9])

In [22]:
4.

4.0

In [25]:
4.0

4.0

In [26]:
array1 = np.array([4,5,6,8.9])
array1

array([4. , 5. , 6. , 8.9])

In [29]:
array1 = np.array([4,5,6,8,3+5j])
array1

array([4.+0.j, 5.+0.j, 6.+0.j, 8.+0.j, 3.+5.j])

In [32]:
array1 = np.array([4,5,6,8,5.6,'10.45'])
array1

array(['4', '5', '6', '8', '5.6', '10.45'], dtype='<U32')

In [34]:
array1 = np.array([4,'5',6,8,5.6])
array1

array(['4', '5', '6', '8', '5.6'], dtype='<U32')

In [36]:
array1 = np.array([4,5.1,6,8,9])
array1

array([4. , 5.1, 6. , 8. , 9. ])

In [38]:
array1 = np.array([4, 5.1, 6, 8, 9])
array1

array([4. , 5.1, 6. , 8. , 9. ])

In [40]:
array1 = np.array([4, 5.12456, 6, 8, 9])
array1

array([4.     , 5.12456, 6.     , 8.     , 9.     ])

### Type Casting in Numpy

In [ ]:
int >> float
float >> int
int >> complex
float >> complex
complex !>> int
complex !>> float

In [44]:
array1 = np.array([4, 5, 6, 8, 9])
array1.dtype

dtype('int32')

In [47]:
array1 = np.array([4, 5, 6, 8, 9], dtype = float)
array1

array([4., 5., 6., 8., 9.])

In [49]:
array1 = np.array([4, 5, 6, 8, 9], dtype = complex)
array1

array([4.+0.j, 5.+0.j, 6.+0.j, 8.+0.j, 9.+0.j])

In [51]:
array1 = np.array([4, 5, 6, 8, 9], dtype = str)
array1

array(['4', '5', '6', '8', '9'], dtype='<U1')

In [53]:
array1 = np.array([4, 5, 6, 8, 9], dtype = 'float')
array1

array([4., 5., 6., 8., 9.])

In [55]:
array1 = np.array([4, 5, 6, 8, 9], dtype = 'complex')
array1

array([4.+0.j, 5.+0.j, 6.+0.j, 8.+0.j, 9.+0.j])

In [57]:
array1 = np.array([4, 5, 6, 8, 9], dtype = complex)
array1

array([4.+0.j, 5.+0.j, 6.+0.j, 8.+0.j, 9.+0.j])

In [59]:
array1 = np.array([4, 5.45, 6, 8.12, 9])
array1

array([4.  , 5.45, 6.  , 8.12, 9.  ])

In [63]:
array1 = np.array([4, 5.45, 6, 8.12, 9])
array1.dtype

dtype('float64')

In [64]:
int(5.45)

5

In [67]:
array1 = np.array([4, 5.45, 6, 8.12, 9], dtype = int)
array1

array([4, 5, 6, 8, 9])

In [69]:
array1 = np.array([4, 5.45, 6, 8.12, 9], dtype = complex)
array1

array([4.  +0.j, 5.45+0.j, 6.  +0.j, 8.12+0.j, 9.  +0.j])

In [71]:
array1 = np.array([4, 5 +4j, 5, 6, 8.12, 9])
array1

array([4.  +0.j, 5.  +4.j, 5.  +0.j, 6.  +0.j, 8.12+0.j, 9.  +0.j])

In [74]:
array1 = np.array([4, 5 +4j, 5, 6, 8.12, 9])
array1.dtype

dtype('complex128')

In [77]:
x = 2 + 5j
int(x)

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'complex'

In [79]:
x = 2 + 5j
float(x)

TypeError: float() argument must be a string or a real number, not 'complex'

In [81]:
x = '3456.67'
float(x)

3456.67

In [83]:
array1 = np.array([4, 5 +4j, 5, 6, 8.12, 9], dtype = int)
array1

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'complex'

In [85]:
array1 = np.array([4, 5 +4j, 5, 6, 8.12, 9], dtype = str)
array1

array(['4', '(5+4j)', '5', '6', '8.12', '9'], dtype='<U6')

### array.ndim

In [88]:
arr1 = np.array([2,3,4,5,6,7])
arr1

array([2, 3, 4, 5, 6, 7])

In [92]:
arr1.ndim

2

In [93]:
x = [[2,3,4],[5,6,7]]
x

[[2, 3, 4], [5, 6, 7]]

In [94]:
arr1 = np.array([[2,3,4],[5,6,7]])
arr1

array([[2, 3, 4],
       [5, 6, 7]])

In [96]:
arr1 = np.array([[2,3,4],[5,6,7]])
arr1.ndim

2

In [99]:
arr1 = np.array([[[2,3,4],[5,6,7]]])
arr1

array([[[2, 3, 4],
        [5, 6, 7]]])

In [101]:
arr1 = np.array([[[2,3,4],[5,6,7]]])
arr1.ndim

3

In [103]:
arr1 = np.array(15)
arr1.ndim

0

In [105]:
arr1 = np.array(15,30)
arr1.ndim

TypeError: Cannot interpret '30' as a data type

In [107]:
arr1 = np.array([15,30])
arr1.ndim

1

In [109]:
arr1 = np.array([15,30,5,6,7])
arr1

array([15, 30,  5,  6,  7])

In [112]:
arr1 = np.array([[15,30,5,6,7]])
print("Number of dimensions :",arr1.ndim)
arr1

Number of dimensions : 2


array([[15, 30,  5,  6,  7]])

In [114]:
arr1 = np.array([15,30,5,6,7])
print("Number of dimensions :",arr1.ndim)
arr1

Number of dimensions : 1


array([15, 30,  5,  6,  7])

In [116]:
arr1 = np.array([15,30,5,6,7], ndmin = 3)
print("Number of dimensions :",arr1.ndim)
arr1

Number of dimensions : 3


array([[[15, 30,  5,  6,  7]]])

In [118]:
arr1 = np.array([15,30,5,6,7], ndmin = 2)
print("Number of dimensions :",arr1.ndim)
arr1

Number of dimensions : 2


array([[15, 30,  5,  6,  7]])

In [120]:
arr1 = np.array([15,30,5,6,7], ndmin = 0)
print("Number of dimensions :",arr1.ndim)
arr1

Number of dimensions : 1


array([15, 30,  5,  6,  7])

In [122]:
arr1 = np.array([[15,30],[5,6]])
print("Number of dimensions :",arr1.ndim)
arr1

Number of dimensions : 2


array([[15, 30],
       [ 5,  6]])

In [124]:
arr1 = np.array([[15,30],[5,6]], ndmin = 1)
print("Number of dimensions :",arr1.ndim)
arr1

Number of dimensions : 2


array([[15, 30],
       [ 5,  6]])

In [126]:
arr1 = np.array([[15,30],[5,6]], ndmin = 4)
print("Number of dimensions :",arr1.ndim)
arr1

Number of dimensions : 4


array([[[[15, 30],
         [ 5,  6]]]])

In [130]:
arr1 = np.array([[15,30],[5,6],[10,20]])
arr1

array([[15, 30],
       [ 5,  6],
       [10, 20]])

In [132]:
arr1 = np.array([[15,30],[5,6],[10,20],[7,8]])
arr1

array([[15, 30],
       [ 5,  6],
       [10, 20],
       [ 7,  8]])

In [134]:
arr1 = np.array([[15,30],[5,6],[10,20],[7,8,9]])
arr1

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [ ]:
[[15, 30],
[ 5,  6,  8],
[10, 20],
[ 7,  8]]

In [136]:
arr1 = np.array([[15,30],[5,6],[10,20],[7]])
arr1

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [137]:
arr1 = np.array([[15,30],[5,6],[10,20],[7]])
arr1

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [138]:
a1 = np.array(5)
a1.ndim

0

In [139]:
a1 = np.array([5,7,8,9,2])
a1.ndim

1

In [141]:
a1 = np.array([[5,7,8,9,2],[50,70,80,90,20]])
a1.ndim

2

In [143]:
a1 = np.array([[5,7,8,9,2],[50,70,80,90,20],[500,700,800,900,200]])
a1.ndim

2

In [145]:
a1 = np.array([[5,7,8,9,2],[50,70,80,90,20],[500,700,800,900,200]])
a1

array([[  5,   7,   8,   9,   2],
       [ 50,  70,  80,  90,  20],
       [500, 700, 800, 900, 200]])

In [147]:
a1 = np.array([[[5,7,8,9,2],[50,70,80,90,20]],[[51,71,81,91,21],[501,710,810,901,210]]])
a1.ndim

3

In [149]:
a1 = np.array([[[5,7,8,9,2],[50,70,80,90,20]],[[51,71,81,91,21],[501,710,810,901,210]]])
a1

array([[[  5,   7,   8,   9,   2],
        [ 50,  70,  80,  90,  20]],

       [[ 51,  71,  81,  91,  21],
        [501, 710, 810, 901, 210]]])

[12, 14, 15, 17, 19, 30]

In [203]:
a1 = np.array([5,7,8,9,2])
a1.ndim

1

In [205]:
a1 = np.array([5,7,8,9,2])
a1.shape

(5,)

In [206]:
a1 = np.array([[5,7,8],[9,2,4]])
a1

array([[5, 7, 8],
       [9, 2, 4]])

In [208]:
a1 = np.array([[5,7,8],[9,2,4]])
a1.ndim

2

In [211]:
a1.shape

(2, 3)

In [213]:
a1 = np.array([[5,7,8,9,2],[50,70,80,90,20],[500,700,800,900,200]])
a1

array([[  5,   7,   8,   9,   2],
       [ 50,  70,  80,  90,  20],
       [500, 700, 800, 900, 200]])

In [215]:
a1.ndim

2

In [217]:
a1.shape

(3, 5)

### Mathematical operations

In [154]:
print(list1 * 5)

[12, 14, 15, 17, 19, 30, 12, 14, 15, 17, 19, 30, 12, 14, 15, 17, 19, 30, 12, 14, 15, 17, 19, 30, 12, 14, 15, 17, 19, 30]


In [158]:
list1 = [12,14,15,17,19,30]
# list1 / 5
new_list = [i/5 for i in list1]
new_list

[2.4, 2.8, 3.0, 3.4, 3.8, 6.0]

In [159]:
list1 = [12,14,15,17,19,30]
# list1 / 5
new_list = [i+100 for i in list1]
new_list

[112, 114, 115, 117, 119, 130]

In [162]:
list1 = [12,14,15,17,19,30]
arr2 = np.array(list1)
arr2 + 10 # 12 + 10, 14 + 10

array([22, 24, 25, 27, 29, 40])

In [164]:
list1 = [12,14,15,17,19,30]
arr2 = np.array(list1)
arr2 / 5

array([2.4, 2.8, 3. , 3.4, 3.8, 6. ])

In [174]:
list1 = [12,14,15,17,19,30]
arr2 = np.array(list1)
arr2 / 5

array([2.4, 2.8, 3. , 3.4, 3.8, 6. ])

### Array to List

In [168]:
x = np.array([2.4, 2.8, 3. , 3.4, 3.8, 6. ])
x.tolist()

[2.4, 2.8, 3.0, 3.4, 3.8, 6.0]

In [170]:
x = np.array([2.4, 2.8, 3. , 3.4, 3.8, 6. ])
list(x)

[2.4, 2.8, 3.0, 3.4, 3.8, 6.0]

In [172]:
a1 = np.array([[[5,7,8,9,2],[50,70,80,90,20]],[[51,71,81,91,21],[501,710,810,901,210]]])
a1

array([[[  5,   7,   8,   9,   2],
        [ 50,  70,  80,  90,  20]],

       [[ 51,  71,  81,  91,  21],
        [501, 710, 810, 901, 210]]])

In [175]:
a1 * 10

array([[[  50,   70,   80,   90,   20],
        [ 500,  700,  800,  900,  200]],

       [[ 510,  710,  810,  910,  210],
        [5010, 7100, 8100, 9010, 2100]]])

### np.iinfo()

In [177]:
np.iinfo(int)

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [180]:
np.iinfo('int8')

iinfo(min=-128, max=127, dtype=int8)

In [181]:
x = 45

In [183]:
np.iinfo('int16')

iinfo(min=-32768, max=32767, dtype=int16)

In [185]:
np.iinfo('int32')

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [187]:
np.iinfo('int64')

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [190]:
# np.iinfo('int128')

In [218]:
# np.iinfo('float64')

In [220]:
array1 = np.array([[3,4,5,6,7],[3,4,5,6,7]])
array1

array([[3, 4, 5, 6, 7],
       [3, 4, 5, 6, 7]])

In [221]:
array1 = np.array([[3,4,5,6,7],[3,4,5.1,6,7]])
array1

array([[3. , 4. , 5. , 6. , 7. ],
       [3. , 4. , 5.1, 6. , 7. ]])