### Numpy-Linear Algebra

In [1]:
import numpy as np

In [ ]:
1. np.linalg:
    1. np.linalg.solve()
    2. np.linalg.det()
    3. np.linalg.inv()
    4. np.linalg.eigvals()
    5. np.linalg.eig()

2. np.polynomial.Polynomial():
    eq.roots()


In [ ]:
2x + 3y = 10
5x + 8y = 30
x = ? -10
y = ? 10

In [ ]:
2x + 3y + 5z= 10
5x + 8y + 10z= 30
4x + 7y + 8z= 30

x = ? -10
y = ? 10
z = ?

In [ ]:
2x + 3y = 10
5x + 8y = 30

2 * -10 + 3 * 10 >> 10

In [ ]:
matrx >> 2-dimensional array

In [3]:
arr = np.array([[3,4],[7,8]])
arr

array([[3, 4],
       [7, 8]])

In [5]:
arr = np.array([[3,4,5],[7,8,7]])
arr

array([[3, 4, 5],
       [7, 8, 7]])

### 1. np.linalg.solve()

In [ ]:
2x + 3y = 10
5x + 8y = 30

In [8]:
arrayA = np.array([[2,3],[5,8]])
arrayA

array([[2, 3],
       [5, 8]])

In [9]:
arrayB =  np.array([10,30])

In [11]:
np.linalg.solve(arrayA,arrayB)

array([-10.,  10.])

In [ ]:
2x + 3y + 5z= 10
5x + 8y + 10z = 30
4x + 7y + 8z = 20


In [13]:
arrayA = np.array([[2,3,5],[5,8,10],[4,7,8]])
arrayA

array([[ 2,  3,  5],
       [ 5,  8, 10],
       [ 4,  7,  8]])

In [15]:
arrayB =  np.array([10,30,20])
arrayB

array([10, 30, 20])

In [16]:
np.linalg.solve(arrayA,arrayB)

array([23.33333333, -6.66666667, -3.33333333])

In [18]:
4 * 23.33 + 7*-6.67 + 8*-3.33

19.989999999999995

### Deteminant of Matrix

In [ ]:
A = a   b
    c   d

|A| = ad-bc

In [20]:
arrayA = np.array([[2,3],[5,8]])
arrayA

array([[2, 3],
       [5, 8]])

In [21]:
np.linalg.det(arrayA)

1.0000000000000009

In [23]:
arrayA = np.array([[2,3,5],[5,8,10],[4,7,8]])
arrayA

array([[ 2,  3,  5],
       [ 5,  8, 10],
       [ 4,  7,  8]])

In [25]:
np.linalg.det(arrayA)

2.9999999999999982

### Inverse of matrix 

In [26]:
arrayA = np.array([[2,3],[5,8]])
arrayA

array([[2, 3],
       [5, 8]])

In [27]:
np.linalg.inv(arrayA)

array([[ 8., -3.],
       [-5.,  2.]])

In [28]:
arrayA = np.array([[2,3,5],[5,8,10],[4,7,8]])
np.linalg.inv(arrayA)

array([[-2.        ,  3.66666667, -3.33333333],
       [ 0.        , -1.33333333,  1.66666667],
       [ 1.        , -0.66666667,  0.33333333]])

### eigen values and eigen vector

In [ ]:
PCA

In [29]:
arrayA = np.array([[2,3],[5,8]])
arrayA

array([[2, 3],
       [5, 8]])

In [32]:
np.linalg.eigvals(arrayA)

array([0.10102051, 9.89897949])

In [34]:
eigenvalues, eigenvectors = np.linalg.eig(arrayA)

In [36]:
eigenvalues

array([0.10102051, 9.89897949])

In [37]:
eigenvectors

array([[-0.84494897, -0.35505103],
       [ 0.53484692, -0.93484692]])

### Polynomial equations

In [ ]:
x2 -5x + 6 = 0
x = 3 , 2
x - 3 = 0 >> x = 3
9 - 15 + 6 = 0

x - 2 = 0 >> x = 2
4 - 10 + 6 = 0

ax2 + bx + c = 0

x1 = -b+np.sqrt(b2 - 4ac)/2a

In [41]:
from numpy.polynomial import Polynomial
# x2 -5x + 6 = 0
a = 1
b = -5
c = 6
eq = Polynomial([c,b,a])
eq.roots()

array([2., 3.])

In [42]:
# 3x^3 + 5x^2 -10x + 15 = 0
eq = Polynomial([15,-10,5,3])
eq.roots()

array([-3.19792459+0.j        ,  0.76562896-0.98859817j,
        0.76562896+0.98859817j])

In [44]:
arrayA = np.array([2,3,5,8])
arrayA[2] = 500
arrayA

array([  2,   3, 500,   8])

In [45]:
arrayA = np.array([2,3,5,8])
arrayA + 4

array([ 6,  7,  9, 12])